baseURL = "https://choquality.github.io/"
title = "코몽이"
languageCode = "en"
enableInlineShortcodes = true
theme = "soho"

summarylength = 10
enableEmoji = true

[params]
author = "Author Name"
#description = ""

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/kmong.png"

copyright = "Author Name"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"

## Set custom CSS and/or JS to override site defaults.
#customCss = ["css/blog.css"]
#customJs = ["js/blog.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "#"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "#"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "#"

[menu]

  [[menu.main]]
  name = "정리?"
  weight = 100
  identifier = "1"
  description = "정리?"
  url = "/posts/"

  [[menu.main]]
  name = "미정?"
  weight = 200
  identifier = "2"
  description = "미정?"
  url = "/undefined/"

  [[menu.main]]
  name = "생각?"
  identifier = "3"
  weight = 300
  description = "생각?"
  url = "/about/"

  [[menu.main]]
  name = "참고?"
  weight = 400
  identifier = "4"
  description = "참고?"
  url = "/sites/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4

